baseURL: 'https://timurblog.netlify.app'
languageCode: 'en-us'
title: "Timur's Profile"
theme: hugo-profile

outputs:
  home:
    - 'HTML'
    - 'RSS'
    - 'JSON'
  page:
    - 'HTML'
    - 'RSS'

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Timur's Profile"
  description: Portfolio for Timur Izbasarov
  # staticPath: ""  # The path to serve the static files from
  favicon: '/fav.png'

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Timur's Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: 'Hi, my name is'
    title: 'Timur.'
    subtitle: 'I build cutting-edge web applications.'
    content: "I am a passionate software developer specializing in both Web 2.0 and Web 3.0 technologies. With a strong focus on single-page applications (SPA) and blockchain-based websites, I create solutions that are innovative, efficient, and future-ready. Whether it's crafting seamless user experiences or developing robust decentralized applications, I bring modern web technologies to life."
    image: /images/me.jpg
    bottomImage:
      enable: true
    #roundImage: true # Make hero image circular | default false

    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/trane7776
        - icon: fab fa-x-twitter
          url: https://x.com/trane7776

  # About
  about:
    enable: true
    title: 'About Me'
    image: '/images/me1.jpg'
    content: |-
      I am an enthusiastic software developer with a strong passion for both Web 2.0 and Web 3.0 technologies. With a solid background in computer science and mathematics, I am fascinated by the intersection of technology and innovation. Despite not having formal work experience, I have been actively engaged in freelance projects that showcase my skills and dedication.

      My expertise includes building sophisticated single-page applications (SPA) using modern frameworks and developing secure, efficient blockchain-based websites. I have hands-on experience with Next.js, Solidity, smart contract testing, and the Ethers.js library. Additionally, I am proficient in integrating and using MetaMask for decentralized applications.

      As a freelancer, I have successfully completed multiple projects that required me to leverage my technical skills and problem-solving abilities to deliver high-quality solutions. I am committed to continuing my growth and contributing to innovative projects in the web development space.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - 'HTML'
        - 'CSS'
        - 'Tailwind'
        - 'JavaScript'
        - 'React'
        - 'Node.js'
        - 'Express'
        - 'Mongoose'
        - 'Prisma'
        - 'Next.js'
        - 'Solidity'
        - 'Ethers.js'
        - 'MetaMask'
        - 'Hardhat'

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: 'Freelance Web Developer'
        company: 'Freelance'
        companyUrl: '#'
        date: 'Jan 2022 - present'
        featuredLink:
          enable: true
          name: 'View the projects'
          url: 'https://github.com/trane7776'
        content: 'I am currently working as a freelance web developer specializing in both Web 2.0 and Web 3.0 technologies.'

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: 'Lower post-secondary vocational education of Computer Science'
        school:
          name: 'Tver Colledge of Economics'
          url: 'https://tverpek.ru/'
        date: '2017 - 2021'
      - title: 'Bachelor of Mathematical Software and System Administration, Computer Science'
        school:
          name: 'Plekhanov Russian University of Economics'
          url: 'https://rea.ru'
        date: '2022 - Present'

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: 'https://github.com/gurusabarish/hugo-profile'
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Blockchain-Based Real Estate Agency with Smart Contracts and NFTs
        content: Imagine a real estate platform like Zillow, but enhanced with the cutting-edge technology of blockchain, smart contracts, and NFTs.
        image: /images/projects/millow.png

        badges:
          - 'Ethereum'
          - 'Solidity'
          - 'React'
          - 'Ethers.js'
          - 'Hardhat'
          - 'Metamask'
          - 'IPFS'
        links:
          - icon: fab fa-github
            url: https://github.com/trane7776/millow
      - title: Design App
        content: This project is a web application for creating and publishing T-shirt designs. Users can register, create unique T-shirt designs using various tools, publish their works, and comment on other users' designs.
        image: /images/projects/design.png
        featured:
          name: Demo
          link: https://design-shirt-app.netlify.app/
        badges:
          - 'React'
          - 'Three.js'
          - 'Express'
        links:
          - icon: fab fa-github
            url: https://github.com/trane7776/design-react-app
      - title: Migleor Chat
        content: A P2P communication application for video calls. It works through WebRTC using simple-peer, with a server based on socket.io.
        image: /images/projects/migleor.png
        featured:
          name: Demo
          link: https://video-chat-app-sooty.vercel.app/
        badges:
          - 'React'
          - 'Socket.io'
          - 'Peer.js'
          - 'Express'
        links:
          - icon: fab fa-github
            url: https://github.com/trane7776/video-chat-app

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:timatitimati1@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: 'blogs'
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/trane7776
      twitter: https://x.com/trane7776
      vk: https://vk.com/trane7776
      tg: https://t.me/t_r_a_n_e

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: 'min read'
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: 'Read'
    toc: 'Table Of Contents'
    copyright: 'All rights reserved'
    pageNotFound: 'Page not found'
    emailText: 'Check out this site'

  datesFormat:
    article: 'Jan 2, 2006'
    articleList: 'Jan 2, 2006'
    articleRecent: 'Jan 2, 2006'

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
